### ISSUE TITLE
Launch on startup no longer working on macOS

### ISSUE THREAD

**Issue by lexpostma** [homebridge/homebridge#2464]
**Describe Your Problem:**
I had a working Homebridge setup that launched in the background when my Mac started. After running updates to my Homebridge setup (npm update for it and all plugins), this launch on startup stopped working. 

The command `launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist` executed, but Homebridge does not start. It does start without issues manually in the Terminal. This command used to work.

Then I read about `hb-service` and removed my entire Homebridge setup to go with the new, easier route of `sudo hb-service install` but it didn't start anything. The message did read:
```
ℹ Installing Homebridge Service
ℹ Starting Homebridge Service...
✔ Homebridge Started

Manage Homebridge by going to one of the following in your browser:

* http://localhost:8080
* http://192.168.2.2:8080
* http://[fe80::404:46fb:1125:232]:8080

Default Username: admin
Default Password: admin

✔ Homebridge Setup Complete
```
But nothing started. The `.homebridge` folder wasn't created and Homebridge UI was not available. When doing `sudo hb-service start` it says:
```
ℹ Starting Homebridge Service...
/Library/LaunchDaemons/com.homebridge.server.plist: service already loaded
✔ Homebridge Started
```

After a manual `homebridge` it ran a cleanly installed Homebridge. I quit it and moved all config files back. So my setup is working again, but still not in the background.

Any idea how I can get it to launch on startup in the background?

Could it be related to this warning during installation?
`npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)`

**Logs:**
`hb-service logs` gives:
```
✖ ERROR: Log file does not exist at expected location: /Users/Lex/.homebridge/homebridge.log
```

**Environment:**

* **Node.js Version**: v12.16.1
* **NPM Version**: 6.14.4
* **Homebridge Version**: 0.4.53
* **Operating System**: macOS 10.15.4
* **Process Supervisor**: I wish I knew. I think it should be `hb-service`, but that's not working

**Comment by donavanbecker** [comment]
Did you try [rebuilding hb-service](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#major-nodejs-version-updates) after npm updates?

**Comment by lexpostma** [comment]
Hi. I did, but just to be sure I just did it again.

After `sudo hb-service rebuild` I did `sudo hb-service restart`, resulting in:
```
ℹ Restarting Homebridge Service
ℹ Stopping Homebridge Service...
✔ Homebridge Stopped
ℹ Starting Homebridge Service...
✔ Homebridge Started
```
But Homebridge is not actually running. Homebridge UI is not available and in Activity Monitor there's no Homebridge.

**Comment by oznu** [comment]
Can you show the contents of this file:

/Library/LaunchDaemons/com.homebridge.server.plist

**Comment by lexpostma** [comment]
Sure, the contents of `/Library/LaunchDaemons/com.homebridge.server.plist` is this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/node</string>
             <string>/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js</string>
             <string>run</string>
             <string>-I</string>
             <string>-U</string>
             <string>/var/root/.homebridge</string>
        </array>
    <key>StandardOutPath</key>
        <string>/var/root/.homebridge/homebridge.log</string>
    <key>StandardErrorPath</key>
        <string>/var/root/.homebridge/homebridge.log</string>
    <key>UserName</key>
        <string>Lex</string>
    <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
                <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands</string>
            <key>HOME</key>
                <string>/var/root</string>
            <key>UIX_STORAGE_PATH</key>
                <string>/var/root/.homebridge</string>
        </dict>
</dict>
</plist>
```

Full disclosure and just spitballing: I also change the name on my internal SSD. On Catalina the disks are split, so their names no longer match.

**Comment by oznu** [comment]
Strange, it's managed to figure out the username, "Lex" for the username key, but hasn't correctly resolved the home directory for that user.

During my testing of standard installs on Mojave and Catalina this worked fine.

Try this:

```
sudo hb-service uninstall
sudo hb-service install -U /Users/Lex/.homebridge
```

**Comment by lexpostma** [comment]
It works!!

Only remaining (new) problem is a restart loop, probably because this:
```
[3/29/2020, 8:05:38 AM] [HttpWebHooks] Initializing HttpWebHooks platform...
[3/29/2020, 8:05:38 AM] Error: EROFS: read-only file system, mkdir '/.node-persist'
    at Object.mkdirSync (fs.js:840:3)
    at sync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/mkdirp/index.js:78:24)
    at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:600:20)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-http-webhooks/node_modules/node-persist/src/node-persist.js:37:32)
    at new HttpWebHooksPlatform (/usr/local/lib/node_modules/homebridge-http-webhooks/index.js:55:16)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
[3/29/2020, 8:05:38 AM] [homebridge-plex-sensors.Plex] Homebridge Plex Sensors listening for webhooks on: http://<homebridge ip>:22987
[3/29/2020, 8:05:38 AM] Got SIGTERM, shutting down Homebridge...
```

Does not happen in manual mode, but does with hb-service. Copied from Homebridge logs on front page of UI.

**Comment by oznu** [comment]
I'm going to release a bug fix to prevent this happening for other users. In the meantime,  I think you need to edit the `/Library/LaunchDaemons/com.homebridge.server.plist` file and fix the HOME env variable.

```
sudo nano /Library/LaunchDaemons/com.homebridge.server.plist
```

It's probably still set to:

```
<key>HOME</key>
  <string>/var/root</string>
```

Change this to:

```
<key>HOME</key>
  <string>/Users/Lex</string>
```

Then restart:

```
sudo hb-service restart
```

**Comment by lexpostma** [comment]
Edited, it was indeed still `/var/root`. But that did not fix the restart loop. Same error in the logs.

**Comment by oznu** [comment]
Can you show the full thing again?

```
/Library/LaunchDaemons/com.homebridge.server.plist
```

**Comment by lexpostma** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/node</string>
             <string>/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js</string>
             <string>run</string>
             <string>-I</string>
             <string>-U</string>
             <string>/Users/Lex/.homebridge</string>
        </array>
    <key>StandardOutPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>UserName</key>
        <string>Lex</string>
    <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
                <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands</string>
            <key>HOME</key>
                <string>/Users/Lex</string>
            <key>UIX_STORAGE_PATH</key>
                <string>/Users/Lex/.homebridge</string>
        </dict>
</dict>
</plist>
```

**Comment by oznu** [comment]
In the `homebridge-http-webhooks` plugin config set the cache directory (the plugin should really just store files in the homebridge storage directory).

```json
"platforms": [
  {
    "platform": "HttpWebHooks",
    "cache_directory": "/Users/Lex/.homebridge/http-webhooks"
```

And make that directory for good measure:

```bash
# do not use sudo
mkdir /Users/Lex/.homebridge/http-webhooks
```

Then restart.

**Comment by lexpostma** [comment]
That fixed it. Thank you @oznu! I really appreciate your (crazy fast) help 🥇

**Comment by oznu** [comment]
Actually, can you test this for me instead?

Rather than manually adding the cache_directory to that plugin, edt the `/Library/LaunchDaemons/com.homebridge.server.plist` file again and add this key:

```
<key>WorkingDirectory</key>
    <string>/Users/Lex/.homebridge</string>
```

You can add that under this section,

```
<key>UserName</key>
    <string>Lex</string>
```

**Comment by lexpostma** [comment]
That also works.

I removed the cache_directory line from `config.json` and deleted the `/Users/Lex/.homebridge/http-webhooks` directory.

This is the `/Library/LaunchDaemons/com.homebridge.server.plist` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/node</string>
             <string>/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js</string>
             <string>run</string>
             <string>-I</string>
             <string>-U</string>
             <string>/Users/Lex/.homebridge</string>
        </array>
    <key>StandardOutPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>UserName</key>
        <string>Lex</string>
    <key>WorkingDirectory</key>
        <string>/Users/Lex/.homebridge</string>
    <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
                <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands</string>
            <key>HOME</key>
                <string>/Users/Lex</string>
            <key>UIX_STORAGE_PATH</key>
                <string>/Users/Lex/.homebridge</string>
        </dict>
</dict>
</plist>
```

**Comment by oznu** [comment]
Thanks! That will be two bugs fixed in the next release 😄

**Comment by oznu** [comment]
I will have a test release up soon, do you think you could try that out once it is?

**Comment by lexpostma** [comment]
Perfect! Do I close the issue? Or do you want to close it when the bug fixes are released.

Sure, I can try the test release.

**Comment by oznu** [comment]
Thanks!

First, uninstall the service.

```
sudo hb-service uninstall
```

Then install the `@test` version of `homebridge-config-ui-x`:

```
sudo npm install -g homebridge-config-ui-x@test
```

Then run the install command again, just as the wiki says, without the extra `-U`:

```
sudo hb-service install
```

Once that's done, please copy the contents of `/Library/LaunchDaemons/com.homebridge.server.plist` here once more so I can check it's all good.

**Comment by lexpostma** [comment]
Done. Result:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>RunAtLoad</key>
        <true/>
    <key>KeepAlive</key>
        <true/>
    <key>Label</key>
        <string>com.homebridge.server</string>
    <key>ProgramArguments</key>
        <array>
             <string>/usr/local/bin/node</string>
             <string>/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js</string>
             <string>run</string>
             <string>-I</string>
             <string>-U</string>
             <string>/Users/Lex/.homebridge</string>
        </array>
    <key>WorkingDirectory</key>
         <string>/Users/Lex/.homebridge</string>
    <key>StandardOutPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>StandardErrorPath</key>
        <string>/Users/Lex/.homebridge/homebridge.log</string>
    <key>UserName</key>
        <string>Lex</string>
    <key>EnvironmentVariables</key>
        <dict>
            <key>PATH</key>
                <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands</string>
            <key>HOME</key>
                <string>/Users/Lex</string>
            <key>UIX_STORAGE_PATH</key>
                <string>/Users/Lex/.homebridge</string>
        </dict>
</dict>
</plist>
```

**Comment by oznu** [comment]
Great. That looks all good. Is everything working as expected?

**Comment by lexpostma** [comment]
Yes, everything works as expected.

**Comment by oznu** [comment]
Thanks for your help fixing this. It will be published to everyone in this weeks release - once the update goes live you will still see an update notification in the UI which will take you back to the non-test stream.

**Comment by lexpostma** [comment]
Perfect, thanks again!
