### ISSUE TITLE
Version 1.0.1 All went offline

### ISSUE THREAD

**Issue by bleedr** [homebridge/homebridge#2529]
Just updated, perfectly working before, now nothing works (raps 3b+):
```

[4/28/2020, 00:07:12] [Config] Rebooting linux server with command: "sudo -n shutdown -r now"
[4/28/2020, 00:07:13] [HB Supervisor] Stopping services...
[4/28/2020, 00:07:13] Got SIGTERM, shutting down Homebridge...
[4/28/2020, 00:07:13] [Temperature & Humidity] Stopped scanning.
[4/28/2020, 00:07:13] [Temperature & Humidity] Stop scanning. (poweredOff)
[4/28/2020, 00:07:15] [Temperature & Humidity] Start scanning.
[4/28/2020, 00:07:16] [Temperature & Humidity] Error: Could not start scanning, state is poweredOff (not poweredOn)
    at Noble.scan (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:97:19)
    at Noble.startScanning (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:126:10)
    at Scanner.start (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:36:13)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:72:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[4/28/2020, 00:07:18] [Config] Terminal session ended.
[4/28/2020, 00:07:40] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[4/28/2020, 00:07:40] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[4/28/2020, 00:07:40] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/28/2020, 00:07:40] [HB Supervisor] Started Homebridge with PID: 649
[4/28/2020, 00:07:42] Loaded config.json with 6 accessories and 3 platforms.
[4/28/2020, 00:07:42] ---
[4/28/2020, 00:07:45] Loaded plugin: homebridge-config-ui-x
[4/28/2020, 00:07:45] Registering platform 'homebridge-config-ui-x.config'
[4/28/2020, 00:07:45] ---
[4/28/2020, 00:07:45] Loaded plugin: homebridge-mi-hygrothermograph
[4/28/2020, 00:07:50] [Config] Homebridge Config UI X v4.16.0 is listening on :: port 8080
[4/28/2020, 00:07:53] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[4/28/2020, 00:07:53] ---
[4/28/2020, 00:08:03] Loaded plugin: homebridge-platform-wemo
[4/28/2020, 00:08:03] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[4/28/2020, 00:08:03] ---
[4/28/2020, 00:08:04] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.5
[4/28/2020, 00:08:04] Registering platform 'homebridge-tahoma.Tahoma'
[4/28/2020, 00:08:04] ---
[4/28/2020, 00:08:05] Loaded plugin: homebridge-mqtt-switch-tasmota
[4/28/2020, 00:08:05] Plugin '@bluephlame/homebridge-mqtt-switch-tasmota' tried to register with an incorrect plugin identifier: 'homebridge-mqtt-switch-tasmota'. Please report this to the developer!
[4/28/2020, 00:08:05] Registering accessory '@bluephlame/homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[4/28/2020, 00:08:05] ---
[4/28/2020, 00:08:05] Loading 3 platforms...
[4/28/2020, 00:08:05] [WeMo] Initializing BelkinWeMo platform...
[4/28/2020, 00:08:05] [My TaHoma Box] Initializing Tahoma platform...
[4/28/2020, 00:08:05] [My TaHoma Box] Fetch accessories...
[4/28/2020, 00:08:05] [My TaHoma Box] Login Connexoon server...
[4/28/2020, 00:08:05] [Config] Initializing config platform...
[4/28/2020, 00:08:05] [Config] Running in Service Mode
[4/28/2020, 00:08:05] Loading 6 accessories...
[4/28/2020, 00:08:05] [Schlafzimmer] Initializing mqtt-switch-tasmota accessory...
[4/28/2020, 00:08:05] [Schlafzimmer] Nazwa do RESULT  POWER
[4/28/2020, 00:08:05] [Leo's Zimmer] Initializing mqtt-switch-tasmota accessory...
[4/28/2020, 00:08:05] [Leo's Zimmer] Nazwa do RESULT  POWER
[4/28/2020, 00:08:05] [Vorne] Initializing mqtt-switch-tasmota accessory...
[4/28/2020, 00:08:05] [Vorne] Nazwa do RESULT  POWER1
[4/28/2020, 00:08:05] [Hinten] Initializing mqtt-switch-tasmota accessory...
[4/28/2020, 00:08:05] [Hinten] Nazwa do RESULT  POWER2
[4/28/2020, 00:08:05] [Balkon] Initializing mqtt-switch-tasmota accessory...
[4/28/2020, 00:08:05] [Balkon] Nazwa do RESULT  POWER3
[4/28/2020, 00:08:05] [Temperature & Humidity] Initializing Hygrotermograph accessory...
[4/28/2020, 00:08:05] [Temperature & Humidity] address option is not set. When running multiple sensors this will cause interference. See README for instructions.
[4/28/2020, 00:08:06] [My TaHoma Box] Unable to refresh states (not logged in)
[4/28/2020, 00:08:06] [WeMo] Online: LED Kueche [08863BC5D1CC]
[4/28/2020, 00:08:06] [WeMo] Online: LED Flur [08863BC5E3B8]
[4/28/2020, 00:08:06] [WeMo] Online: WeMo Motion [08863BC4A58C]
[4/28/2020, 00:08:06] [Temperature & Humidity] Start scanning.
[4/28/2020, 00:08:07] [My TaHoma Box] [Box] type: Pod > Pod, protocol: internal
[4/28/2020, 00:08:07] [My TaHoma Box] No definition found for Pod > Pod in mapping.json file
[4/28/2020, 00:08:07] [My TaHoma Box] [Küche] type: RollerShutter > PositionableRollerShutter, protocol: io
[4/28/2020, 00:08:07] [My TaHoma Box] Instanciate Küche as WindowCovering
[4/28/2020, 00:08:07] [My TaHoma Box] [Leo] type: RollerShutter > PositionableRollerShutter, protocol: io
[4/28/2020, 00:08:07] [My TaHoma Box] Instanciate Leo as WindowCovering
[4/28/2020, 00:08:07] [My TaHoma Box] [Schlafzimmer] type: RollerShutter > PositionableRollerShutter, protocol: io
[4/28/2020, 00:08:07] [My TaHoma Box] Instanciate Schlafzimmer as WindowCovering
[4/28/2020, 00:08:07] [My TaHoma Box] [Wohnzimmer Tür] type: RollerShutter > PositionableRollerShutter, protocol: io
[4/28/2020, 00:08:07] [My TaHoma Box] Instanciate Wohnzimmer Tür as WindowCovering
[4/28/2020, 00:08:07] [My TaHoma Box] [Wohnzimmer Fenster] type: RollerShutter > PositionableRollerShutter, protocol: io
[4/28/2020, 00:08:07] [My TaHoma Box] Instanciate Wohnzimmer Fenster as WindowCovering
[4/28/2020, 00:08:07] Initializing platform accessory 'Wohnzimmer Fenster'...
[4/28/2020, 00:08:07] Initializing platform accessory 'Wohnzimmer Tür'...
[4/28/2020, 00:08:07] Initializing platform accessory 'Schlafzimmer'...
[4/28/2020, 00:08:07] Initializing platform accessory 'Leo'...
[4/28/2020, 00:08:07] Initializing platform accessory 'Küche'...
Setup Payload:
X-HM://0023QSNASLK4B
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
```

I removed Homebridge in hope of fixing the problem, and tried to readd, no matter if I delete the persists and accessories or simply create a new user -> Homebridge can't be connected, no connection to that device :(

Please advise! Maybe how can I roll back?

**Comment by lucyan90** [comment]
all Accessory was offline, everything seems start great. I use docker version in raspberry Pi 4 (Buster).

i downgraded from container and now works well with 0.4.53 version

**Comment by xBotRaid** [comment]
I had my Homebridge running for about 4 weeks on my Server running  Windows 10. Suddenly everything lost connection. All accessories „not responding“, then I deleted them... Now I cannot get Homebridge to be recognized by any of my iOS Devices, it keeps on failing to find the old accessories. Then I deleted the Homebridge config and tried to do reconnect, also cannot find anything related to my Server inside the Bonjour Browser on the iPhone or iPad on the same Network.

I tried so many suggestions written in Forums and I'll give you a quick recap with links  on what I've already done:

* Deleted persist and accessories folder and all plugins - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
* Changed username, pin, name and port + reinstall of Node and HomeKit  - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
* Reconfigured WIFI - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#home-couldnt-connect-to-this-accessory)
* Disabled IPv6 in Windows Network Adapter Settings (in forum they did it on Raspbian) - [Can't Pair GitHub Comment](https://github.com/nfarina/homebridge/issues/607#issuecomment-236471712)
* Examined logs for plugin errors - [mDNS packets GitHub Comment](https://github.com/nfarina/homebridge/issues/1957#issuecomment-497756617)
* Run Debug Mode (no errors found) - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#debug-mode)
* Changed Network interface (ethernet adapter instead of built in port - no success either) - [GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-427690849)
* Specified mDNS local Server-IP inside config file - [mDNS packets Comment GitHub](https://github.com/nfarina/homebridge/issues/1957#issuecomment-468709606)
* Checked if port is open via command (worked) - ["Homebridge Running but..." GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-378514491)
* Opened Homebridge Port and Bonjour Ports (UDP: 1900 , 5350, 5351, 5353) in Windows Firewall
* Reset network configuration

I tried literally anything I found online, but no success. Many things are done inside of a Linux based system, mine is on Windows so sometimes a bit difficult to research. How can I solve this... I have been searching for too long now.

Please help...

&#x200B;

Testing config if necessary:

    {
      "mdns": { "interface": "192.168.0.10" },
      "bridge": {
        "name": "MyHomebridge",
        "username": "BB:21:1B:B3:AB:BA",
        "port": 51820,
        "pin": "439-56-562"
      },
      "accessories": [
    		{
             "accessory": "StatefulDummySwitch",
             "name": "My Switch 1"
            }
      ],
    
      "platforms": [
      ]
    }

**Comment by JSVarga** [comment]
I have been running to a while then upgraded to latest version. It failed. Try to manually install package, failed. Try to delete and reinstall 1.0.7 and it won't run but still has same version number. Here are the error messages from the log.

[4/28/2020, 12:44:09 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c0fc8d68-7c06-40ce-b5ea-554fc650a021
at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
at /usr/local/lib/node_modules/homebridge/src/server.ts:287:19
at Array.filter ()
at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:268:69)
at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:10)
at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:1156:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
at Module.load (internal/modules/cjs/loader.js:1000:32)
at Function.Module._load (internal/modules/cjs/loader.js:899:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at internal/main/run_main_module.js:18:47

**Comment by fezzz** [comment]
For me the problem was, that the new version connects port 51826 to the IPv6 address only.
check this with 

sudo netstat -an | grep 51826

Changing one line in the code of the eventlistener, which is part of an included library in homebridge made the change (node_modules/homebridge/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js ) :

this._tcpServer.listen(targetPort);

change to:

this._tcpServer.listen(targetPort, '0.0.0.0');

Credits go to: 
https://github.com/homebridge/homebridge/issues/1277

**Comment by vgr28** [comment]
Same on Version 1.0.2

**Comment by JSVarga** [comment]
UPDATE: I decided to take the step of resetting, which would mean paring again with HomeKit. It actually worked a treat. After resetting Homebridge ran on v1.0.2 and I did have to pair and set things in the Home app but not reconfigure Homebridge. Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that. My Ring Doorbell, Visonic alarm and Harmony remote hub all working fine now.

**Comment by bleedr** [comment]
A bit OT, but can you tell me what is the sense of adding the Sonos Boxes to Homebridge? I've 8 boxes and am using the Sonos App only, with Homebridge you can't really use them, or can you? Thanks!

> UPDATE: I decided to take the step of resetting, which would mean paring again with HomeKit. It actually worked a treat. After resetting Homebridge ran on v1.0.2 and I did have to pair and set things in the Home app but not reconfigure Homebridge. Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that. My Ring Doorbell, Visonic alarm and Harmony remote hub all working fine now.

**Comment by JSVarga** [comment]
I agree, it wasn't until I added the plug in that I realised the limited functionality. The only benefit I have found is to turn them off, either using Siri or in a Scene. Also, and I know this is trivial, but when my CONNECT:Amps are stacked turning the LED on/off to identify them helps but nothing that couldn't be fixed with a label! Otherwise I use the Sonos app too.

**Comment by k411e** [comment]
I am using the docker image. I added to my startup.sh the followed line:
`sed -i.bak "s/this._tcpServer.listen(targetPort);/this._tcpServer.listen(targetPort, '0.0.0.0');/" /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js`

After container restart the file was updated and I get now also a ipv4 address:
`netstat -an | grep 51826  
tcp        0      0 0.0.0.0:51826           0.0.0.0:*               LISTEN     `

Unfortunately it's still not working. All my devices are offline.
What can I check additionally?

**Comment by ebaauw** [comment]
>  Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that.

I haven't tried Homebridge v1.0.2 yet, but I don't expect any issues.  Homebridge ZP v1.0.27 works with Homebridge v1.0.1.  Please open an issue for Homebridge ZP, attaching the debug log.

> I agree, it wasn't until I added the plug in that I realised the limited functionality. The only benefit I have found is to turn them off, either using Siri or in a Scene.

See the [README](https://github.com/ebaauw/homebridge-zp): Homebridge ZP provides way more functionality than that.  I've fully integrated my Sonos system with my other smart devices using Homebridge ZP: automatically dimming the lights when turning on the TV; music following me from room to room, as I walk through my house, control the Sonos players (volume up/down, next previous input/favourite, next/previous track) through Zigbee wireless switches, etc.  Not everything is supported by Apple's Home app, though.

**Comment by hoefs** [comment]
> > Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that.
> 
> I haven't tried Homebridge v1.0.2 yet, but I don't expect any issues. Homebridge ZP v1.0.27 works with Homebridge v1.0.1. Please open an issue for Homebridge ZP, attaching the debug log.
> 
> > I agree, it wasn't until I added the plug in that I realised the limited functionality. The only benefit I have found is to turn them off, either using Siri or in a Scene.
> 
> See the [README](https://github.com/ebaauw/homebridge-zp): Homebridge ZP provides way more functionality than that. I've fully integrated my Sonos system with my other smart devices using Homebridge ZP: automatically dimming the lights when turning on the TV; music following me from room to room, as I walk through my house, control the Sonos players (volume up/down, next previous input/favourite, next/previous track) through Zigbee wireless switches, etc. Not everything is supported by Apple's Home app, though.

In homebridge everything is working fine 1.0.2 and the latest ZP. But the home.app still shows everything as no response. Rolling back to 0.4.53 breaks ZP as it needs 1.0.0 or greater.
The issue with homebridge looks like a communication issue on docker/synology
Now I am running a stable homebridge 0.4.53 and ZP 1.0.26. This works really good.

**Comment by JSVarga** [comment]
> > Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that.
> 
> I haven't tried Homebridge v1.0.2 yet, but I don't expect any issues. Homebridge ZP v1.0.27 works with Homebridge v1.0.1. Please open an issue for Homebridge ZP, attaching the debug log.
> 
> > I agree, it wasn't until I added the plug in that I realised the limited functionality. The only benefit I have found is to turn them off, either using Siri or in a Scene.
> 
> See the [README](https://github.com/ebaauw/homebridge-zp): Homebridge ZP provides way more functionality than that. I've fully integrated my Sonos system with my other smart devices using Homebridge ZP: automatically dimming the lights when turning on the TV; music following me from room to room, as I walk through my house, control the Sonos players (volume up/down, next previous input/favourite, next/previous track) through Zigbee wireless switches, etc. Not everything is supported by Apple's Home app, though.

All working now, resaved settings and restarted Homebridge. I realised there are imitations but through the Home App all I seem to be able to do is start/stop and change volume. I have looked at the EVE app with offers lots of controls but then why not just use the Sonos app? I thought the whole idea of HomeKit to to minimise control points. How do you control the inputs?

**Comment by OwlBawl** [comment]
Got the same problem on 1.0.2
All devices are active in Web, but in Home App - offline

made "sudo netstat -an | grep 51826" 
`pi@raspberrypi:~ $ sudo netstat -an | grep 52826
tcp        0      0 127.0.0.1:32854         127.0.0.1:52826         TIME_WAIT  
tcp        0      0 192.168.1.200:47486     192.168.1.200:52826     ESTABLISHED
tcp6       0      0 :::52826                :::*                    LISTEN     
tcp6       0      0 192.168.1.200:52826     192.168.1.200:47486     ESTABLISHED
tcp6       0      0 192.168.1.200:52826     192.168.1.37:53808      ESTABLISHED
tcp6       0      0 127.0.0.1:52826         127.0.0.1:32864         TIME_WAIT  
tcp6       0      0 127.0.0.1:52826         127.0.0.1:32872         TIME_WAIT  
tcp6       0      0 192.168.1.200:52826     192.168.1.101:57792     ESTABLISHED
tcp6       0      0 127.0.0.1:52826         127.0.0.1:32858         TIME_WAIT  
tcp6       0      0 192.168.1.200:52826     192.168.1.81:62125      ESTABLISHED
tcp6       0      0 192.168.1.200:52826     192.168.1.103:50637     ESTABLISHED
tcp6       0      0 192.168.1.200:52826     192.168.1.125:49240     ESTABLISHED
tcp6       0      0 127.0.0.1:52826         127.0.0.1:32868         TIME_WAIT`

What should i do next?

**Comment by vgr28** [comment]
> 
> 
> > > Only issue is the Sonos ZP plug in does not seem to be working but not overly worried about that.
> > 
> > 
> > I haven't tried Homebridge v1.0.2 yet, but I don't expect any issues. Homebridge ZP v1.0.27 works with Homebridge v1.0.1. Please open an issue for Homebridge ZP, attaching the debug log.
> > > I agree, it wasn't until I added the plug in that I realised the limited functionality. The only benefit I have found is to turn them off, either using Siri or in a Scene.
> > 
> > 
> > See the [README](https://github.com/ebaauw/homebridge-zp): Homebridge ZP provides way more functionality than that. I've fully integrated my Sonos system with my other smart devices using Homebridge ZP: automatically dimming the lights when turning on the TV; music following me from room to room, as I walk through my house, control the Sonos players (volume up/down, next previous input/favourite, next/previous track) through Zigbee wireless switches, etc. Not everything is supported by Apple's Home app, though.
> 
> In homebridge everything is working fine 1.0.2 and the latest ZP. But the home.app still shows everything as no response. Rolling back to 0.4.53 breaks ZP as it needs 1.0.0 or greater.
> The issue with homebridge looks like a communication issue on docker/synology
> Now I am running a stable homebridge 0.4.53 and ZP 1.0.26. This works really good.

I'm also back to 0.4.53 . Everthing working fine...

**Comment by mtressl** [comment]
I tried everything, neither 1.0.0 or 1.0.1 nor 1.0.2 can be added to the Home.app
Sitting there without HomeKit integration.

**Comment by Supereg** [comment]
@mtressl would you bind trying the latest 1.0.3 beta (specifically 1.0.3-beta.5)?

**Comment by mtressl** [comment]
> @mtressl (and anybody else) would you bind trying the latest version (1.0.3) and check if your issues still persist

YES! That did the trick.

**Comment by Mibra-de** [comment]
With the update to 1.0.3 I have the same issue. Home App had no Connection. I use hombridge on the Docker from my Synology.
What should i do ?

**Comment by OwlBawl** [comment]
Thanks for update 1.0.3 - it did the trick )
By the way, now devices status (in 1.0.3) are showing instantly, while on 0.4 had to wait refresh

**Comment by wojo** [comment]
Hmm, updated to 1.0.3 running on Docker but still only binding to IPv6

```
root@nas:~# sudo netstat -an | grep 52423
tcp6       0      0 :::52423                :::*                    LISTEN
```

This is via Docker on Synology, dual stack IPv6 and IPv4.

**Comment by luc-ass** [comment]
Same problem here. Homebridge 1.0.3 on Synology NAS inside onzu/docker-homebridge. Downgrade to 1.0.2, 1.0.1, 1.0.0 and 0.4.53 made no difference. It worked perfectly until I upgraded...

**Comment by mickgiles** [comment]
I downgraded to 1.0.0 and everything came back. Will wait for an official solution until I upgrade again

**Comment by donavanbecker** [comment]
Did you all try v1.0.4?

**Comment by mickgiles** [comment]
I did. I went straight from 1.0.0 to 1.0.4 and it broke. I didn't try any of the in between builds

**Comment by wojo** [comment]
@donavanbecker v1.0.4 fixed it for me!

**Comment by Supereg** [comment]
@bleedr may you verify that the issue still persist for you on the latest version of homebridge.

@mickgiles you could may outline what exact issue you experiencing?

**Comment by mickgiles** [comment]
I upgraded from 1.0.0 to 1.0.4 and all of my accessories disappeared from the gui (homebridge-config-ui-x v4.17.1) and were not responding from homekit on my device. 
`sudo netstat -an | grep 51826`  showed that it was only binding to ipv6 however I have ipv6 disable on my box (ubuntu). 
Reverting back to 1.0.0 restored full functionality
Happy to test anything that might help you chase this down

**Comment by Supereg** [comment]
@mickgiles So you have 1.0.0 running smoothly? I don't quite get the issues with HAP-NodeJS only binding on ipv6. On one hand the section of the code never changed.

From the docs:
`
If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
`

I would assume when you say, that you disabled ipv6, it should bind automatically to `0.0.0.0`?

Additionally the docs says
`
In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).
`

This is also referred to dual-stack mode and seems to be os specific.
I will investigate this. My Pi for example will just bind on :: tcp6 but will perfectly accept any request done via it's ipv4 addresses.

You are not running in a vm or something are you? I pushed an update to the underlying bonjour library a few hours ago, it will automatically install the latest version if you reinstall 1.0.4. But doesn't sound like this would have any influence on your described problem.

**Comment by mickgiles** [comment]
Not running in a VM. Just tried installing latest again and everything works fine now.
Either this is transient or your bonjour fix resolved it. I'll report back if I have any more problems.

**Comment by Supereg** [comment]
Weird, love those errors which just disappear 😅

**Comment by Supereg** [comment]
Okay, did some testing. And it seems like when binding to :: (or leaving out the hostname) it will just bind to ipv4, tested on my macOS machine and on my Pi running raspbian. I would assume the same behavior on ubuntu(?). On macOS netstat shows `tcp46` to indicate dual-stack support, on raspbian it only lists `tcp6` but will accept `tcp` just the same way. If we would change to listen to `0.0.0.0` we would eliminate the possibility at all to listen to tcp6.

**Comment by Supereg** [comment]
@wojo seemed to have similar issues with latest 1.0.4 resolving it. So maybe it really was an issue with bonjour advertising?

**Comment by iondarie** [comment]
Running Homebridge on a RPI4, on the latest 1.0.4 all the devices are not responding. No errors in the log.

If i access the web interface for homebridge all accessories start working again for 30-40minutes and then they all become not responsive once again.

**Comment by FoUStep** [comment]
In a Debian 10 VM (w/ ipv6 disabled) with HomeBridge 1.0.4 after changing the following in the file below:
`/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/util/eventedhttp.js`

`this._tcpServer.listen(targetPort);`
changed into: 
`this._tcpServer.listen(targetPort, '0.0.0.0');`

I can see that it no longer does tcp6 but just tcp (so that looks good and also ESTABLISHED and 0.0.0.0 on LISTEN.

However it still doesn't work. Updating and not responding.

**Comment by Eightplant** [comment]
I was fine through 1.03 but 1.04 broke my installation.
I tried the eventedhttp.js fix but that did not work for me.
I reverted that eventedhttp.js change and shut down the VM I run homebridge on and bounced my router as I was too impatient to wait for any connections to die on their own.
Upon startup I see 51420 connected to a tcp v4 port and video came alive again on my phone in a seperate VLAN!

**Comment by FoUStep** [comment]
Apparently all is fine if I restore a VM backup to 0.4.53 and update to 1.04! It seems the new Domoticz version (2020.2+) is the culprit. Running perfectly on 1.04 combined with Domoticz 2020.1 now.

**Comment by glowfishDE** [comment]
I think this issue is the same or related to issue #2564
