### ISSUE TITLE
Homebridge Docker not working 'functions-have-names'

### ISSUE THREAD

**Issue by stoffLer** [homebridge/homebridge#3433]
### Analysis

[9/13/2023, 12:50:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/13/2023, 12:50:15 PM] [HB Supervisor] Restarting Homebridge...
[9/13/2023, 12:50:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[9/13/2023, 12:50:15 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 5839
Error: Cannot find module 'functions-have-names'
Require stack:
- /opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/implementation.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/deep-equal/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/helpers.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /opt/homebridge/lib/node_modules/homebridge/lib/cli.js
- /opt/homebridge/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
[9/13/2023, 12:50:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null

### Expected Behavior

running HB...

### Steps To Reproduce

Install Docker Version of HB 

### Logs

```markdown
[9/13/2023, 12:50:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9/13/2023, 12:50:15 PM] [HB Supervisor] Restarting Homebridge...
[9/13/2023, 12:50:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[9/13/2023, 12:50:15 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 5839
Error: Cannot find module 'functions-have-names'
Require stack:
- /opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/implementation.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/regexp.prototype.flags/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/deep-equal/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/helpers.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /opt/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /opt/homebridge/lib/node_modules/homebridge/lib/cli.js
- /opt/homebridge/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/homebridge/node_modules/set-function-name/index.js:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
[9/13/2023, 12:50:16 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
```

### Configuration

```json
stock
```

### Environment

- OS: Docker on Ubuntu
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by stoffLer** [comment]
-> npm install functions-have-names

**Comment by stoffLer** [comment]
closed

**Comment by jkossis** [comment]
@stoffLer  I think this issue needs to be re-opened, as manually installing that dependency isn't the answer here. It should be included in the docker image.

**Comment by jkossis** [comment]
@Supereg any way we can get this re-opened?

**Comment by NorthernMan54** [comment]
@jkossis @stoffLer pls re-open against the docker-homebridge repo, and include instructions to recreate the issue.

tks

**Comment by stoffLer** [comment]
done

**Comment by jarekpelczynski** [comment]
have the same issue running HB on Synology DSM

**Comment by jkossis** [comment]
I'll open the issue in the docker repo

**Comment by BOB-DK** [comment]
@stoffLer 
I have tried: npm install functions-have-names
That didn't solve my problem, Homebridge status is still not running.

Is there another way I can solve the problem?

**Comment by jkossis** [comment]
@BOB-DK are you executing that within the container, and not the host? It should work as a temporary fix.
